[package]
name = "compiler"
version = "0.1.0"
authors = ["nate <nate.givens03@gmail.com>"]
edition = "2018"

[dependencies]
scanner = { path = "../scanner" }
fancy-scanner = { path = "../fancy-scanner" }
parser = { path = "../parser" }
