[package]
name = "fancy-scanner"
version = "0.1.0"
authors = ["Nathan Givens <nate.givens03@gmail.com>"]
edition = "2018"

[dependencies]
fancy-regex = "0.1.0"
lazy_static = "*"
num = "*"
num-derive = "*"
num-traits = "*"
